export const domains = [
  { id: 'ikigai', name: 'IKIGAI', weight: 0.25, questionRange: [1, 20] },
  { id: 'personality', name: 'PERSONALITY', weight: 0.10, questionRange: [21, 45] },
  { id: '16p', name: '16 PERSONALITIES', weight: 0.10, questionRange: [46, 60] },
  { id: 'decision', name: 'DECISION MAKING', weight: 0.20, questionRange: [61, 80] },
  { id: 'financial', name: 'FINANCIAL DECISION', weight: 0.20, questionRange: [81, 100] },
  { id: 'change', name: 'CHANGE DIRECTION', weight: 0.15, questionRange: [101, 120] },
]

export const questions = [
  // IKIGAI Q1-Q20 (scale 1-5)
  { id: 1, domain: 'ikigai', type: 'scale', text: 'I wake up most mornings feeling excited about my day' },
  { id: 2, domain: 'ikigai', type: 'scale', text: 'I have a clear sense of what I am passionate about' },
  { id: 3, domain: 'ikigai', type: 'scale', text: 'I regularly engage in activities that make time feel like it flies' },
  { id: 4, domain: 'ikigai', type: 'scale', text: 'My hobbies and interests energise rather than drain me' },
  { id: 5, domain: 'ikigai', type: 'scale', text: 'I find joy in the small moments of my daily routine' },
  { id: 6, domain: 'ikigai', type: 'scale', text: 'I believe my life has a deeper purpose beyond just survival' },
  { id: 7, domain: 'ikigai', type: 'scale', text: 'I feel I am contributing something meaningful to others' },
  { id: 8, domain: 'ikigai', type: 'scale', text: 'The world would be slightly different if I had not existed' },
  { id: 9, domain: 'ikigai', type: 'scale', text: 'I act on my values even when it is difficult' },
  { id: 10, domain: 'ikigai', type: 'scale', text: 'I can articulate why my life matters in a few sentences' },
  { id: 11, domain: 'ikigai', type: 'scale', text: 'I am being paid (or could be paid) to do what I am good at' },
  { id: 12, domain: 'ikigai', type: 'scale', text: 'My core skills are recognised and valued by others' },
  { id: 13, domain: 'ikigai', type: 'scale', text: 'I invest time in developing my professional competencies' },
  { id: 14, domain: 'ikigai', type: 'scale', text: 'My career aligns with my natural strengths' },
  { id: 15, domain: 'ikigai', type: 'scale', text: 'I feel confident in my ability to create economic value' },
  { id: 16, domain: 'ikigai', type: 'scale', text: 'What I do serves a genuine need in the world' },
  { id: 17, domain: 'ikigai', type: 'scale', text: 'People come to me because of a specific value I provide' },
  { id: 18, domain: 'ikigai', type: 'scale', text: "I feel my work makes others' lives better" },
  { id: 19, domain: 'ikigai', type: 'scale', text: 'I can see how my efforts create impact beyond myself' },
  { id: 20, domain: 'ikigai', type: 'scale', text: 'My daily work contributes to something larger than me' },

  // PERSONALITY Q21-Q36 (A/B choice)
  { id: 21, domain: 'personality', type: 'choice', optionA: 'I feel energised after spending time alone', optionB: 'I feel energised after spending time with others' },
  { id: 22, domain: 'personality', type: 'choice', optionA: 'I prefer small, deep conversations', optionB: 'I enjoy large group interactions' },
  { id: 23, domain: 'personality', type: 'choice', optionA: 'I trust facts and concrete details', optionB: 'I trust patterns and future possibilities' },
  { id: 24, domain: 'personality', type: 'choice', optionA: 'I prefer step-by-step instructions', optionB: 'I prefer to figure things out as I go' },
  { id: 25, domain: 'personality', type: 'choice', optionA: 'I make decisions based on logic', optionB: 'I make decisions based on how people feel' },
  { id: 26, domain: 'personality', type: 'choice', optionA: 'I value truth over tact', optionB: 'I value harmony over being right' },
  { id: 27, domain: 'personality', type: 'choice', optionA: 'I like to have plans and stick to them', optionB: 'I like to stay flexible and adapt' },
  { id: 28, domain: 'personality', type: 'choice', optionA: 'I feel stressed leaving things unfinished', optionB: 'I feel energised by open possibilities' },
  { id: 29, domain: 'personality', type: 'choice', optionA: 'I prefer working independently', optionB: 'I prefer collaborating with others' },
  { id: 30, domain: 'personality', type: 'choice', optionA: 'I prefer realistic and practical ideas', optionB: 'I prefer creative and abstract ideas' },
  { id: 31, domain: 'personality', type: 'choice', optionA: 'I stay objective even in emotional situations', optionB: 'I naturally empathise in emotional situations' },
  { id: 32, domain: 'personality', type: 'choice', optionA: 'I find it easy to give critical feedback', optionB: 'I find it hard to say something that might upset others' },
  { id: 33, domain: 'personality', type: 'choice', optionA: 'I usually follow a schedule', optionB: 'I usually go with the flow' },
  { id: 34, domain: 'personality', type: 'choice', optionA: 'I like to decide things quickly', optionB: 'I prefer to keep options open' },
  { id: 35, domain: 'personality', type: 'choice', optionA: 'I need alone time to recharge after social events', optionB: 'Social events leave me wanting more interaction' },
  { id: 36, domain: 'personality', type: 'choice', optionA: 'I notice details before seeing the big picture', optionB: 'I see patterns and connections before details' },

  // PERSONALITY OCEAN Q37-Q45 (scale 1-5)
  { id: 37, domain: 'personality', type: 'scale', text: 'I enjoy trying new and unfamiliar experiences' },
  { id: 38, domain: 'personality', type: 'scale', text: 'I am drawn to creative, artistic, or philosophical ideas' },
  { id: 39, domain: 'personality', type: 'scale', text: 'I complete tasks thoroughly and on time' },
  { id: 40, domain: 'personality', type: 'scale', text: 'I am organised and keep things in order' },
  { id: 41, domain: 'personality', type: 'scale', text: 'I feel comfortable in social situations and enjoy meeting new people' },
  { id: 42, domain: 'personality', type: 'scale', text: 'I often worry about things going wrong' },
  { id: 43, domain: 'personality', type: 'scale', text: "I genuinely care about others' wellbeing" },
  { id: 44, domain: 'personality', type: 'scale', text: "I try to understand other people's perspective before judging" },
  { id: 45, domain: 'personality', type: 'scale', text: 'I get stressed easily in difficult situations' },

  // 16 PERSONALITIES Q46-Q60 (A/B choice)
  { id: 46, domain: '16p', type: 'choice', optionA: 'You prefer to stay in the background', optionB: 'You enjoy being the centre of attention' },
  { id: 47, domain: '16p', type: 'choice', optionA: 'You trust what you can see and measure', optionB: 'You trust your instincts and gut feelings' },
  { id: 48, domain: '16p', type: 'choice', optionA: 'You think with your head, not your heart', optionB: 'You lead with empathy and feelings' },
  { id: 49, domain: '16p', type: 'choice', optionA: 'You prefer having clear plans and routines', optionB: 'You prefer being spontaneous and flexible' },
  { id: 50, domain: '16p', type: 'choice', optionA: 'You rarely second-guess yourself', optionB: 'You often review and reflect on your decisions' },
  { id: 51, domain: '16p', type: 'choice', optionA: 'You prefer working with established methods', optionB: 'You prefer trying new approaches' },
  { id: 52, domain: '16p', type: 'choice', optionA: 'You like things to be concrete and specific', optionB: 'You think in metaphors and abstract concepts' },
  { id: 53, domain: '16p', type: 'choice', optionA: 'You value logic even when it leads to hard truths', optionB: 'You value relationships even over being right' },
  { id: 54, domain: '16p', type: 'choice', optionA: 'You make to-do lists and stick to them', optionB: 'You work best without a fixed plan' },
  { id: 55, domain: '16p', type: 'choice', optionA: 'You recharge better alone', optionB: 'You recharge better with people' },
  { id: 56, domain: '16p', type: 'choice', optionA: 'You prefer practical solutions to big-picture thinking', optionB: 'You prefer vision and strategy over details' },
  { id: 57, domain: '16p', type: 'choice', optionA: 'You analyse before you feel', optionB: 'You feel before you analyse' },
  { id: 58, domain: '16p', type: 'choice', optionA: 'You prefer closure and resolution', optionB: 'You prefer keeping things open' },
  { id: 59, domain: '16p', type: 'choice', optionA: 'You think out loud with others', optionB: 'You think inside your own head first' },
  { id: 60, domain: '16p', type: 'choice', optionA: 'You are confident in most of your life decisions', optionB: 'You frequently wonder if you made the right choice' },

  // DECISION MAKING Q61-Q80 (scale 1-5)
  { id: 61, domain: 'decision', type: 'scale', text: 'Before making a major decision, I clearly define what I am trying to achieve' },
  { id: 62, domain: 'decision', type: 'scale', text: 'I gather enough information before committing to a choice' },
  { id: 63, domain: 'decision', type: 'scale', text: 'I am honest with myself when a decision is not working out' },
  { id: 64, domain: 'decision', type: 'scale', text: 'I consider multiple options before choosing' },
  { id: 65, domain: 'decision', type: 'scale', text: 'I can admit when I am wrong and change course' },
  { id: 66, domain: 'decision', type: 'scale', text: 'I acknowledge when emotions are driving a decision' },
  { id: 67, domain: 'decision', type: 'scale', text: 'I seek feedback from others before important choices' },
  { id: 68, domain: 'decision', type: 'scale', text: 'I reflect on past decisions to learn from them' },
  { id: 69, domain: 'decision', type: 'scale', text: 'I can separate the quality of a decision from its outcome' },
  { id: 70, domain: 'decision', type: 'scale', text: 'I have a consistent process I use for important decisions' },
  { id: 71, domain: 'decision', type: 'scale', text: 'I am comfortable making decisions with incomplete information' },
  { id: 72, domain: 'decision', type: 'scale', text: 'I can articulate the reasoning behind my decisions clearly' },
  { id: 73, domain: 'decision', type: 'scale', text: 'I often second-guess my decisions after making them' },
  { id: 74, domain: 'decision', type: 'scale', text: 'I manage uncertainty without becoming paralysed' },
  { id: 75, domain: 'decision', type: 'scale', text: 'I know when I am the right person to make a decision' },
  { id: 76, domain: 'decision', type: 'scale', text: 'I set time limits on deliberation to avoid overthinking' },
  { id: 77, domain: 'decision', type: 'scale', text: 'I know which factors matter most in a decision before I start' },
  { id: 78, domain: 'decision', type: 'scale', text: 'I distinguish between reversible and irreversible decisions' },
  { id: 79, domain: 'decision', type: 'scale', text: 'I check my assumptions before committing to a course' },
  { id: 80, domain: 'decision', type: 'scale', text: 'I stay decisive even when facing significant pressure' },

  // FINANCIAL DECISION Q81-Q100 (scale 1-5, Q81-Q86 reverse scored)
  { id: 81, domain: 'financial', type: 'scale', text: 'I sometimes hold on to losing investments because I hate realising a loss' },
  { id: 82, domain: 'financial', type: 'scale', text: 'I make financial decisions differently when markets are volatile' },
  { id: 83, domain: 'financial', type: 'scale', text: 'I sometimes make purchases to impress others' },
  { id: 84, domain: 'financial', type: 'scale', text: 'My financial mood is heavily affected by short-term price movements' },
  { id: 85, domain: 'financial', type: 'scale', text: 'I sometimes follow the crowd in financial decisions even if I am unsure' },
  { id: 86, domain: 'financial', type: 'scale', text: 'I feel more pain from losing money than pleasure from gaining the same amount' },
  { id: 87, domain: 'financial', type: 'scale', text: 'I can stay calm and rational during financial downturns' },
  { id: 88, domain: 'financial', type: 'scale', text: 'I distinguish between a bad decision and a bad outcome' },
  { id: 89, domain: 'financial', type: 'scale', text: 'I regularly review my financial decisions to improve' },
  { id: 90, domain: 'financial', type: 'scale', text: 'I set predetermined exit points before entering investments' },
  { id: 91, domain: 'financial', type: 'scale', text: 'I have a clear savings rate that I stick to each month' },
  { id: 92, domain: 'financial', type: 'scale', text: 'I invest according to a long-term plan, not short-term emotion' },
  { id: 93, domain: 'financial', type: 'scale', text: 'I know my net worth and track it regularly' },
  { id: 94, domain: 'financial', type: 'scale', text: 'I understand the difference between assets and liabilities' },
  { id: 95, domain: 'financial', type: 'scale', text: 'I make financial decisions based on evidence, not tips' },
  { id: 96, domain: 'financial', type: 'scale', text: 'I maintain an emergency fund for unexpected expenses' },
  { id: 97, domain: 'financial', type: 'scale', text: 'I understand my own risk tolerance and invest accordingly' },
  { id: 98, domain: 'financial', type: 'scale', text: 'I can calculate the true cost of borrowing before taking debt' },
  { id: 99, domain: 'financial', type: 'scale', text: 'I review my financial plan at least once a year' },
  { id: 100, domain: 'financial', type: 'scale', text: 'I have a written financial goal with a specific timeline' },

  // CHANGE DIRECTION Q101-Q120 (scale 1-5)
  { id: 101, domain: 'change', type: 'scale', text: 'I find it easy to let go of roles or identities that no longer serve me' },
  { id: 102, domain: 'change', type: 'scale', text: 'When something ends in my life, I process the loss before moving on' },
  { id: 103, domain: 'change', type: 'scale', text: 'I can stay resilient through prolonged periods of uncertainty' },
  { id: 104, domain: 'change', type: 'scale', text: 'I bounce back from setbacks faster than most people' },
  { id: 105, domain: 'change', type: 'scale', text: 'I am currently in a period of meaningful personal transition' },
  { id: 106, domain: 'change', type: 'scale', text: 'I have a clear vision of what I am moving toward' },
  { id: 107, domain: 'change', type: 'scale', text: 'I have acknowledged what I am leaving behind in my current transition' },
  { id: 108, domain: 'change', type: 'scale', text: 'I have grieved or processed the ending of a previous chapter' },
  { id: 109, domain: 'change', type: 'scale', text: 'I am taking concrete steps toward my new beginning' },
  { id: 110, domain: 'change', type: 'scale', text: 'I feel more excited than anxious about the changes ahead' },
  { id: 111, domain: 'change', type: 'scale', text: 'I believe my intelligence and abilities can grow with effort' },
  { id: 112, domain: 'change', type: 'scale', text: 'I view failure as feedback, not evidence of fixed limitations' },
  { id: 113, domain: 'change', type: 'scale', text: 'I seek out challenges that push me beyond my comfort zone' },
  { id: 114, domain: 'change', type: 'scale', text: 'I invest time in learning things that are difficult' },
  { id: 115, domain: 'change', type: 'scale', text: 'When I encounter a setback, I analyse it before reacting' },
  { id: 116, domain: 'change', type: 'scale', text: 'I believe people can change their fundamental traits' },
  { id: 117, domain: 'change', type: 'scale', text: 'I surround myself with people who challenge my thinking' },
  { id: 118, domain: 'change', type: 'scale', text: 'I recover from criticism without becoming defensive' },
  { id: 119, domain: 'change', type: 'scale', text: 'I persist through difficult problems rather than avoiding them' },
  { id: 120, domain: 'change', type: 'scale', text: 'I actively seek feedback to improve my blind spots' },
]

export function getQuestionsForDomain(domainId) {
  return questions.filter(q => q.domain === domainId)
}

export function getDomainForQuestion(questionId) {
  const q = questions.find(q => q.id === questionId)
  return q ? q.domain : null
}
